# Generated by Django 6.0.1 on 2026-02-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="review",
            table="reviews",
        ),
    ]
