# Generated by Django 6.0.1 on 2026-02-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lessonprogress"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="course",
            table="courses",
        ),
        migrations.AlterModelTable(
            name="enroll",
            table="enrollments",
        ),
        migrations.AlterModelTable(
            name="lesson",
            table="lessons",
        ),
        migrations.AlterModelTable(
            name="lessonprogress",
            table="lesson_progress",
        ),
    ]
