# Generated by Django 6.0.1 on 2026-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_category_table_alter_course_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
