# Generated by Django 6.0.1 on 2026-02-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="users",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="profiles",
        ),
    ]
